### ISSUE TITLE
wouldn't it be easier to use a grid geometry here?

### ISSUE THREAD

**Issue by marcocuturi** [ingitom99/learn_sink#4]
https://github.com/ingitom99/learn_sink/blob/fe4bef1d39d8c222c32a877fc081a71048702191/src/test_funcs.py#L99

as in https://ott-jax.readthedocs.io/en/latest/tutorials/introduction_grid.html

**Comment by ingitom99** [comment]
It would be easier, I remember I tried to use grid geometry but I kept running into some errors I didn't really understand so I just went around it with PointCloud. I will try again though.

**Comment by marcocuturi** [comment]
happy to help if needed :)
